export const badListing = {
  listing_id: 1174693189,
  state: "active",
  user_id: 586587298,
  category_id: null,
  title:
    "Rare Liberty Cap Half Cent 1794-1797 Full Set 4 pcs American US Coins. Discover now!",
  description:
    "RESTRIKE\nOriginal size, weight and edge!\nMaterial: Metal (Copper)\nFree worldwide shipping",
  creation_tsz: 1645541205,
  ending_tsz: 1655905605,
  original_creation_tsz: 1644226161,
  last_modified_tsz: 1645541205,
  price: "41.50",
  currency_code: "USD",
  quantity: 3,
  sku: [],
  tags: [
    "rare coin",
    "silver dollar",
    "rare coins",
    "old coins",
    "silver half dollar",
    "half dollar",
    "morgan dollar",
    "usa rare coins",
    "liberty dollar",
    "antique coin",
    "american dollar",
    "copy coin",
    "replica coin",
  ],
  materials: [],
  shop_section_id: null,
  featured_rank: null,
  state_tsz: 1644226161,
  url: "https://www.etsy.com/listing/1174693189/rare-liberty-cap-half-cent-1794-1797?utm_source=timelesscurrency&utm_medium=api&utm_campaign=api",
  views: 57,
  num_favorers: 3,
  shipping_template_id: null,
  processing_min: 1,
  processing_max: 2,
  who_made: "i_did",
  is_supply: "false",
  when_made: "2020_2022",
  item_weight: null,
  item_weight_unit: "g",
  item_length: null,
  item_width: null,
  item_height: null,
  item_dimensions_unit: "mm",
  is_private: false,
  style: null,
  non_taxable: false,
  is_customizable: false,
  is_digital: false,
  file_data: "",
  should_auto_renew: true,
  language: "en-US",
  has_variations: false,
  taxonomy_id: 68,
  taxonomy_path: ["Art & Collectibles", "Collectibles", "Coins & Money"],
  used_manufacturer: false,
  is_vintage: false,
};
export const goodListing = {
  listing_id: 1170093296,
  state: "active",
  user_id: 593686757,
  category_id: null,
  title: "1921 Morgan Silver Dollar",
  description:
    "Beautiful 1921 Morgan Silver Dollar Extra fine condition to A/U! From a coin collection. Well kept!",
  creation_tsz: 1645541113,
  ending_tsz: 1655905513,
  original_creation_tsz: 1645541113,
  last_modified_tsz: 1645541114,
  price: "43.00",
  currency_code: "USD",
  quantity: 1,
  sku: [],
  tags: ["Morgan", "Silver", "vintage", "collectible", "Antique"],
  materials: ["Silver"],
  shop_section_id: 36841639,
  featured_rank: null,
  state_tsz: 1645541113,
  url: "https://www.etsy.com/listing/1170093296/1921-morgan-silver-dollar?utm_source=timelesscurrency&utm_medium=api&utm_campaign=api",
  views: 1,
  num_favorers: 0,
  shipping_template_id: 167049058163,
  processing_min: 3,
  processing_max: 5,
  who_made: "someone_else",
  is_supply: "false",
  when_made: "1920s",
  item_weight: null,
  item_weight_unit: "oz",
  item_length: null,
  item_width: null,
  item_height: null,
  item_dimensions_unit: "in",
  is_private: false,
  style: null,
  non_taxable: false,
  is_customizable: false,
  is_digital: false,
  file_data: "",
  should_auto_renew: false,
  language: "en-US",
  has_variations: false,
  taxonomy_id: 68,
  taxonomy_path: ["Art & Collectibles", "Collectibles", "Coins & Money"],
  used_manufacturer: false,
  is_vintage: true,
};
